sudo: required
dist: trusty
language: node_js
node_js:
  - 4
  - 5
  - 6
  - 7
services:
  - mongodb
before_script:
  - npm install -d
branches:
  only:
    - master
script:
  - npm run lint
  - npm test
